sudo: required
services: 
  - docker

before_install:
  - docker build -t raniayqb/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true raniayqb/docker-react npm run test

deploy: 
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-dev"
  env: "Docker-dev-env"
  bucket_name: "elasticbeanstalk-us-east-1-244974373806"
  bucket_path: "docker-dev"
  on:
    branch: master